name: Install NPM deps
description: Installs, using cache, npm dependencies for project


runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        cache: npm
        node-version: 22
        registry-url: https://registry.npmjs.org

    - name: Install npm dependencies
      run: npm ci
      shell: bash 
