name: 'Check code quality'
description: 'Run pre-checks (linting, formatting) and tests (unit) for project'

runs:
  using: 'composite'
  steps:
    - name: 'Check linting'
      run: npm run lint:ci
      shell: bash

    - name: 'Check formatting'
      run: npm run format:ci
      shell: bash

    - name: 'Run unit tests'
      run: npm run test
      shell: bash
