name: 'Pull request'

on:
  pull_request:

jobs:
  check-code-quality:
    name: 'Check code quality'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v4

      - name: 'Setup node'
        uses: ./.github/actions/setup-node

      - name: 'Check code quality'
        uses: ./.github/actions/check-code-quality
