name: 'Pull request'

on:
  pull_request:

jobs:
  check-code-quality:
    name: 'Check code quality'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v4

      - name: 'Setup node.js'
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: 'Install npm dependencies'
        uses: ./.github/actions/install-npm-deps

      - name: 'Check code quality'
        uses: ./.github/actions/check-code-quality
